CREATE DATABASE IF NOT EXISTS FORUM DEFAULT CHARSET utf8 COLLATE utf8_general_ci;
USE FORUM;

CREATE TABLE USER (
  USERID INT PRIMARY KEY,
  PASSWORD VARCHAR(30) NOT NULL ,
  NAME VARCHAR(20),
  NICK VARCHAR(30)
);

CREATE TABLE POST(
  POSTID INT PRIMARY KEY ,
  TITLE VARCHAR(30),
  CONTENT VARCHAR(1000),
  POSTTIME DATETIME,
  POSTERID INT REFERENCES USER(USERID)
);

CREATE TABLE COMMENT (
  COMMENTID INT PRIMARY KEY ,
  CONTENT VARCHAR(1000),
  COMMENTERID INT REFERENCES USER(USERID),
  POSTID INT REFERENCES POST(POSTID),
  COMMENTTIME DATETIME
);

CREATE TABLE IMAGE(
  IMAGEID INT PRIMARY KEY ,
  URL VARCHAR(50) NOT NULL
);